/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STD_TYPES.h"
#include "BIT_Manipulation.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "STK_interface.h"
#include "RTOS_interface.h"

M_GPIO_CONFIG_t LED_Pin0={GPIO_PORTB,
 			                   GPIO_PIN0,
 							   General_Purpose_Output_Mode,
 							   Output_Push_Pull,
 							   Medium_Speed,
 							   No_Pull_Up_or_Down,
 							   AF11 };
M_GPIO_CONFIG_t LED_Pin1={GPIO_PORTB,
 			                   GPIO_PIN1,
 							   General_Purpose_Output_Mode,
 							   Output_Push_Pull,
 							   Medium_Speed,
 							   No_Pull_Up_or_Down,
 							   AF11 };
M_GPIO_CONFIG_t LED_Pin2={GPIO_PORTB,
 			                   GPIO_PIN2,
 							   General_Purpose_Output_Mode,
 							   Output_Push_Pull,
 							   Medium_Speed,
 							   No_Pull_Up_or_Down,
 							   AF11 };
void LED_TOG1(void);
void LED_TOG2(void);
void LED_TOG3(void);

int main(void)
{



    RCC_voidSysClkInit();
 	RCC_voidPeripheralClockEnable(RCC_AHB1,GPIOB);


 	  GPIO_voidInit(&LED_Pin0);
 	  GPIO_voidInit(&LED_Pin1);
 	  GPIO_voidInit(&LED_Pin2);

 	  STK_voidInit();

 	 RTOS_u8CreateTask(LED_TOG1,0,1000,3);
 	 RTOS_u8CreateTask(LED_TOG2,1, 2000,1);
	 RTOS_u8CreateTask(LED_TOG3,2, 3000, 0);


	 RTOS_voidStartOS();
	while(1)
	{

	}
}

void LED_TOG1(void){
	static u8 x = 0;
	GPIO_SetPinValue(&LED_Pin0, x);
	x = 1 - x;
}

void LED_TOG2(void){
	static u8 x = 0;
	GPIO_SetPinValue(&LED_Pin1, x);
	x = 1 - x;
}

void LED_TOG3(void){
	static u8 x = 0;
	GPIO_SetPinValue(&LED_Pin2, x);
	x = 1 - x;
}

