/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STD_TYPES.h"
#include "BIT_Manipulation.h"

#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "PORT_interface.h"
#include "ShiftReg_interface.h"

void delay_ms(u16 Copy_u8Input);

int main(void)
{
	RCC_voidSysClkInit();

    RCC_voidEnablePerClk(RCC_AHB1,AHB1_GPIOA);

    PORT_voidInit();

    u8 SevSeg[10] = {0b00111111,0b00000110,0b01011011,0b01001111,0b01100110,0b01101101,0b01111101,0b00000111,0b01111111,
    0b01101111};
    ShiftRegister SR1={GPIO_PORTA,GPIO_PIN3,GPIO_PORTA,GPIO_PIN2,GPIO_PORTA,GPIO_PIN1,GPIO_PORTA,GPIO_PIN0};
    ShiftRegister SR2={GPIO_PORTA,GPIO_PIN4,GPIO_PORTA,GPIO_PIN2,GPIO_PORTA,GPIO_PIN1,GPIO_PORTA,GPIO_PIN0};

    for(u8 i=0;i<10;i++)
    {
    ShiftRegister_voidSendDataTwo(SR1, SevSeg[i],SR2,SevSeg[9-i]);
    delay_ms(500);
    }
    while(1);
}

void delay_ms(u16 Copy_u8Input)
{
	for(int i = 0; i < 1000 * Copy_u8Input; i++)
	{
		asm("NOP");
	}
}

